### ISSUE TITLE
trigger when scheduled task / USB backup happens?

### ISSUE THREAD

**Issue by mortee** [tomaae/homeassistant-openmediavault#89]
Is there a way to trigger an automation based on events in OMV? I'm thinking primarily about start/finish of scheduled tasks, and e.g. finish of an USB Backup job.

If that's not possible currently, how could it be implemented?

**Comment by tomaae** [comment]
no, it is not possible.
cron jobs are unlikely to be ever possible.
usb backup is a plugin, that is not supported at all by the integration

**Comment by mortee** [comment]
Can't something regarding this be coordinated with th OMV developers? I've found them quite responsive and welcoming.

**Comment by tomaae** [comment]
not really, its not in their scope.
cron jobs are lx, those are not monitored this way and they dont have persistant states.
for plugins, there would have to be significant interest and willing contributors for me to add plugin support and extend framework.

I do not use OMV for years already and I'm keeping this integration maintained just because there is nothing else for HA. It would be a loss for people to not have any way to integrate OMV. However, adding features that require significant research and work is a different story. While it is not something I'm against, it is also something I'm not willing to do as a solo integration developer.

**Comment by mortee** [comment]
OK, fair enough. I'll have to roll with what we have then.
